[env:blackpill_f411]
platform = ststm32
board = blackpill_f411ce
framework = arduino

; --- HIER GEÄNDERT: ST-Link als Upload-Protokoll definieren ---
upload_protocol = stlink

; --- HIER GEÄNDERT: Die alten DFU-Flags deaktivieren ---
; upload_flags = 
;     -d 0483:df11
;     -a 0
;     -s 0x08000000

build_flags = 
    -I src/drivers
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON

lib_deps = 
    nrf24/RF24 @ ^1.6.0
    adafruit/Adafruit BMP280 Library
    adafruit/Adafruit Unified Sensor
    https://github.com/stevemarple/SoftWire.git
    https://github.com/stevemarple/AsyncDelay.git

monitor_speed = 115200

; --- HIER GEÄNDERT: main.cpp aktivieren, transmitter.cpp deaktivieren ---
build_src_filter =
    -<*>
    +<transmitter.cpp>
    +<drivers/lsm6ds3_driver.cpp>
    +<drivers/ssd1306_driver.cpp>
    +<drivers/piezo_buzzer.cpp>
    +<drivers/bmp280_driver.cpp>